var fs = require('fs')
var Coordinator = require('../../src/controllers/Coordinator')
var confObj = require('./confObj')
var coordi = new Coordinator(confObj, process.argv[2], undefined)
coordi.bootstrap()
